import os
import getpass
import socket
from pathlib import Path


PATH_REGISTRY = {
    "ZandauZand": Path("C:/Users/andrew/Documents/machineLearning"),
    "atlandau": Path("/n/home05/atlandau/machine_learning"),
    "Andrews-MacBook-Pro.local": Path("C:/Users/andrew/Documents/MachineLearning/Dominoes-Experiments"),
}


def get_hostname():
    """simple method for getting the hostname of the current machine"""
    return socket.gethostname()


def get_username():
    """simple method for getting the username of the current user"""
    return getpass.getuser()


def local_path():
    """method for defining the local root path for datasets and results"""
    hostname = get_hostname()
    hostname = hostname if hostname in PATH_REGISTRY else get_username()
    if hostname not in PATH_REGISTRY:
        raise ValueError(f"hostname ({hostname}) is not registered in the path registry")
    return PATH_REGISTRY[hostname]


def local_repo_path():
    """
    method for returning local repo path
    (assumes that this module is one below the dominoes package in the main repo folder)
    """
    repo_folder = os.path.dirname(os.path.abspath(__file__)) + "/.."
    return repo_folder


def results_path():
    """directory for storing results of experiments (and saved networks, figures, etc)"""
    return local_path() / "results"


def figure_path():
    """directory for storing figures generated by experiments to be used on the GitHub page"""
    return local_repo_path() / "docs" / "media"
